#ifndef RESMLP_MODEL_H
#define RESMLP_MODEL_H

#include "resmlp_embed.h"
#include "resmlp_crosspatch.h"
#include "resmlp_crosschannel.h"
#include "resmlp_crosschannel_psa.h"
#include "resmlp_outpool.h"

// This redefines the offset within the CrossChannels sublayer
// to be relative to CrossPatch Layer
#define RM_CC_FC_W_BASE_OFFSET (RM_CP_FC_W_OUT_W_OFFSET)
#define RM_CC_FC_BS_BASE_OFFSET (RM_CP_FC_BS_OUT_BS_OFFSET)
#define RM_CC_AFF_W_BASE_OFFSET (RM_CP_AFF_OUT_W_OFFSET)
#define RM_CC_AFF_BS_BASE_OFFSET (RM_CP_AFF_OUT_BS_OFFSET)

// Basically the size of each layer (CrossPatch + CrossChannel)
#define RM_LAYER_AFF_W_OFFSET_PER_LAYER (RM_CC_AFF_OUT_W_OFFSET)
#define RM_LAYER_AFF_BS_OFFSET_PER_LAYER (RM_CC_AFF_OUT_BS_OFFSET)
#define RM_LAYER_FC_W_OFFSET_PER_LAYER (RM_CC_FC_W_OUT_W_OFFSET)
#define RM_LAYER_FC_BS_OFFSET_PER_LAYER (RM_CC_FC_BS_OUT_BS_OFFSET)
#define RM_LAYER_LUT_OFFSET_PER_LAYER (RM_CC_PSA_OUT_LUT_OFFSET)

// Additional offsets per layer
#define RM_LAYER_1_AFF_W_OFFSET 0
#define RM_LAYER_1_AFF_BS_OFFSET 0
#define RM_LAYER_1_FC_W_OFFSET (RM_EM_OUT_W_OFFSET)
#define RM_LAYER_1_FC_BS_OFFSET (RM_EM_OUT_BS_OFFSET)
#define RM_LAYER_1_PSA_LUT_OFFSET 0

#define RM_LAYER_2_AFF_W_OFFSET (RM_LAYER_1_AFF_W_OFFSET + (RM_LAYER_AFF_W_OFFSET_PER_LAYER))
#define RM_LAYER_2_AFF_BS_OFFSET (RM_LAYER_1_AFF_BS_OFFSET + (RM_LAYER_AFF_BS_OFFSET_PER_LAYER))
#define RM_LAYER_2_FC_W_OFFSET (RM_LAYER_1_FC_W_OFFSET + (RM_LAYER_FC_W_OFFSET_PER_LAYER))
#define RM_LAYER_2_FC_BS_OFFSET (RM_LAYER_1_FC_BS_OFFSET + (RM_LAYER_FC_BS_OFFSET_PER_LAYER))
#define RM_LAYER_2_PSA_LUT_OFFSET (RM_LAYER_1_PSA_LUT_OFFSET + (RM_LAYER_LUT_OFFSET_PER_LAYER))

#define RM_LAYER_3_AFF_W_OFFSET (RM_LAYER_1_AFF_W_OFFSET + (2 * (RM_LAYER_AFF_W_OFFSET_PER_LAYER)))
#define RM_LAYER_3_AFF_BS_OFFSET (RM_LAYER_1_AFF_BS_OFFSET + (2 * (RM_LAYER_AFF_BS_OFFSET_PER_LAYER)))
#define RM_LAYER_3_FC_W_OFFSET (RM_LAYER_1_FC_W_OFFSET + (2 * (RM_LAYER_FC_W_OFFSET_PER_LAYER)))
#define RM_LAYER_3_FC_BS_OFFSET (RM_LAYER_1_FC_BS_OFFSET + (2 * (RM_LAYER_FC_BS_OFFSET_PER_LAYER)))
#define RM_LAYER_3_PSA_LUT_OFFSET (RM_LAYER_1_PSA_LUT_OFFSET + (2 * (RM_LAYER_LUT_OFFSET_PER_LAYER)))

#define RM_LAYER_4_AFF_W_OFFSET (RM_LAYER_1_AFF_W_OFFSET + (3 * (RM_LAYER_AFF_W_OFFSET_PER_LAYER)))
#define RM_LAYER_4_AFF_BS_OFFSET (RM_LAYER_1_AFF_BS_OFFSET + (3 * (RM_LAYER_AFF_BS_OFFSET_PER_LAYER)))
#define RM_LAYER_4_FC_W_OFFSET (RM_LAYER_1_FC_W_OFFSET + (3 * (RM_LAYER_FC_W_OFFSET_PER_LAYER)))
#define RM_LAYER_4_FC_BS_OFFSET (RM_LAYER_1_FC_BS_OFFSET + (3 * (RM_LAYER_FC_BS_OFFSET_PER_LAYER)))
#define RM_LAYER_4_PSA_LUT_OFFSET (RM_LAYER_1_PSA_LUT_OFFSET + (3 * (RM_LAYER_LUT_OFFSET_PER_LAYER)))

#define RM_O_LAYER_AFF_W_OFFSET (RM_LAYER_1_AFF_W_OFFSET + (4 * (RM_LAYER_AFF_W_OFFSET_PER_LAYER)))
#define RM_O_LAYER_AFF_BS_OFFSET (RM_LAYER_1_AFF_BS_OFFSET + (4 * (RM_LAYER_AFF_BS_OFFSET_PER_LAYER)))
#define RM_O_LAYER_FC_W_OFFSET (RM_LAYER_1_FC_W_OFFSET + (4 * (RM_LAYER_FC_W_OFFSET_PER_LAYER)))
#define RM_O_LAYER_FC_BS_OFFSET (RM_LAYER_1_FC_BS_OFFSET + (4 * (RM_LAYER_FC_BS_OFFSET_PER_LAYER)))
#define RM_O_LAYER_PSA_LUT_OFFSET (RM_LAYER_1_PSA_LUT_OFFSET + (4 * (RM_LAYER_LUT_OFFSET_PER_LAYER)))

// These will be used to define the AXI port max depths for cosimulations
#define RM_AFF_W_SIZE RM_O_LAYER_AFF_W_OFFSET
#define RM_AFF_BS_SIZE RM_O_LAYER_AFF_BS_OFFSET
#define RM_FC_W_SIZE (RM_O_LAYER_FC_W_OFFSET + (RM_OUTP_FC_W_OUT_W_OFFSET))
#define RM_FC_BS_SIZE (RM_O_LAYER_FC_BS_OFFSET + (RM_OUTP_FC_BS_OUT_BS_OFFSET))
#define RM_PSA_LUT_SIZE RM_O_LAYER_PSA_LUT_OFFSET

#endif // RESMLP_MODEL_H
